### PR TITLE
Top level multi POST

### PR DESCRIPTION
**Pull request by hesselink**
This changes the top level multi handler to be POST only. GET wasn't technically correct, and it's even less so on this branch, since this adds the possibility to do non-GET requests as part of the multi handler.

This is backwards compatibility breaking, and will be a major bump. However, I doubt it will break many things, since we haven't really advertised the top level multi handler.

### CODE REVIEW

**Comment by hesselink** [comment]
@bergmark What's you opinion of this change?

**Comment by bergmark** [comment]
Looks fine to me.

This change will require that you also regenerate clients, right? Does it then make sense to up the lower bound on rest-core in rest-gen?

**Comment by hesselink** [comment]
I don't think this needs regenerated clients, since the clients don't include the top level multi handler (yet).

**Comment by bergmark** [comment]
Alrighty.

**Comment by hesselink** [comment]
I've added `OverloadedStrings` and also removed the unused `Generic` and `Regular` instances and associated extensions. Shall I merge it like this?

**Comment by bergmark** [comment]
Sure!

**Pull request merged**
