### PR TITLE
generalize Snap monad to MonadSnap

### PR DESCRIPTION
**Pull request by theNerd247**
It would be nice to use rest in a snaplet (not just a base snap). I've extended the functionality of `rest-snap` to allow any monad that is an instance of MonadSnap to be used in the apiToHandler' interface.

### CODE REVIEW

**Comment by bergmark** [comment]
Thanks! Looks great.

I added a commit deriving Functor/Applicative/Monad, does that look ok?

**Comment by theNerd247** [comment]
Yup! I'll squash the commits

**Comment by bergmark** [comment]
Cool, though FYI I can choose to squash when merging on github  :)

**Comment by bergmark** [comment]
Was hoping to release this now but travis is having some issues so I'll check in later

**Comment by theNerd247** [comment]
It's not liking the derive generic for ghc 7.10

**Comment by bergmark** [comment]
Hmm, where do you see this? Travis seems happy: https://travis-ci.org/silkapp/rest/builds/295371487

**Comment by theNerd247** [comment]
AH sorry. I thought you were refering to before you merged... nevermind on that comment

**Comment by bergmark** [comment]
Shipped https://hackage.haskell.org/package/rest-snap-0.3.0.0

**Comment by theNerd247** [comment]
will this update automagically on stackage? And will the haddock documentation be generated?

**Comment by bergmark** [comment]
Yepyep, both those steps are automated

**Pull request merged**
